export default {
  RECLAIM_LIST_GET: 'RECLAIM_LIST_GET',
  RECLAIM_LIST_COUNT: 'RECLAIM_LIST_COUNT',
  RECLAIM_DETAIL_GET: 'RECLAIM_DETAIL_GET',
  WORKORDER_RESET: 'WORKORDER_RESET',
  RECLAIM_ADD_DEVICE: 'RECLAIM_ADD_DEVICE',
  RECLAIM_REDUCE_DEVICE: 'RECLAIM_REDUCE_DEVICE',
  RECLAIM_REFUSE: 'RECLAIM_REFUSE',
  RECLAIM_UPDATE_DEVICE_NUM: 'RECLAIM_UPDATE_DEVICE_NUM',
  RECLAIM_TO_RECYCLE: 'RECLAIM_TO_RECYCLE',
  RECLAIM_REVOKE: 'RECLAIM_REVOKE',
  RECLAIM_GET_SCAN_DEVICE: 'RECLAIM_GET_SCAN_DEVICE',
  RECLAIM_CLEAR_DEVICE: 'RECLAIM_CLEAR_DEVICE',
  RECLAIM_GET_PRODECTSICONS: 'RECLAIM_GET_PRODECTSICONS',
  RECLAIM_GET_CHANGEVALUE: 'RECLAIM_GET_CHANGEVALUE'
}
