export default {
  REPAIR_GET_COUNT: 'REPAIR_GET_COUNT',
  WAREHOUSE_DISTRIBUTION_LIST: 'WAREHOUSE_DISTRIBUTION_LIST',
  WAREHOUSE_DISTRIBUTE: 'WAREHOUSE_DISTRIBUTE',
  WAREHOUSE_REPAIR_DETAIL: 'WAREHOUSE_REPAIR_DETAIL',
  WAREHOUSE_REPAIR_CLAIM_TASK: 'WAREHOUSE_REPAIR_CLAIM_TASK',
  WAREHOUSE_REPAIR_RESET_CLAIM: 'WAREHOUSE_REPAIR_RESET_CLAIM'
}
