export default {
  FETCH_GET_RECLAIM_BD_MAX_COUNT: 'FETCH_GET_RECLAIM_BD_MAX_COUNT',
  FETCH_GET_RECLAIM_BD_REASONS: 'FETCH_GET_RECLAIM_BD_REASONS',
  FETCH_GET_RECLAIM_BD_CONTRACT_ADD: 'FETCH_GET_RECLAIM_BD_CONTRACT_ADD'
}
