export default {
  FETCH_GET_MY_SHOP_LIST: 'FETCH_GET_MY_SHOP_LIST',
  FETCH_GET_MY_SHOP_DEVICE_LIST: 'FETCH_GET_MY_SHOP_DEVICE_LIST',
  CLEAN_GET_MY_SHOP_DEVICE_LIST: 'CLEAN_GET_MY_SHOP_DEVICE_LIST',
  FETCH_GET_MY_SHOP_DEVICE_ORDER_LIST: 'FETCH_GET_MY_SHOP_DEVICE_ORDER_LIST',
  FETCH_GET_MY_SHOP_DEVICE_POWERBANK_LIST: 'FETCH_GET_MY_SHOP_DEVICE_POWERBANK_LIST'
}
