export default {
  A_PURCHASE_APPLY_GET_PRODUCTS: 'A_PURCHASE_APPLY_GET_PRODUCTS',
  A_PURCHASE_APPLY_TRIGGER_UPDATE_COUNT: 'A_PURCHASE_APPLY_TRIGGER_UPDATE_COUNT',
  A_PURCHASE_CONFIRMBOOK_GET_APPLY: 'A_PURCHASE_CONFIRMBOOK_GET_APPLY',
  A_PURCHASE_GET_LIST: 'A_PURCHASE_GET_LIST'
}
