export default {
  WORKORDER_RECYLE_GET_LIST: 'WORKORDER_RECYLE_GET_LIST',
  WORKORDER_RECYLE_MAX_GET_LIST: 'WORKORDER_RECYLE_MAX_GET_LIST',
  WORKORDER_RECYLE_SUBMIT: 'WORKORDER_RECYLE_SUBMIT',
  WORKORDER_RECYLE_CLAIM: 'WORKORDER_RECYLE_CLAIM',
  WORKORDER_RECYLE_CONFIRM: 'WORKORDER_RECYLE_CONFIRM',
  WORKORDER_RECYLE_CANCEL: 'WORKORDER_RECYLE_CANCEL',
  WORKORDER_GET_COUNT: 'WORKORDER_GET_COUNT',
  WORKORDER_RESET_LIST: 'WORKORDER_RESET_LIST'
}
