/**
 * Created by fanli on 2017/4/15.
 */
export default {
  B_SHOP_GET_MANAGER: 'B_SHOP_GET_MANAGER',
  B_SHOP_RESET_MANAGER: 'B_SHOP_RESET_MANAGER',
  B_SHOP_SET_MANAGER: 'B_SHOP_SET_MANAGER',
  B_SHOP_DELETE_MANAGER: 'B_SHOP_DELETE_MANAGER'
}
