export default {
  B_HOME_GET: 'B_HOME_GET',
  B_ACCOUNT_GET_SMS_CODE: 'B_ACCOUNT_GET_SMS_CODE',
  B_SMS_COUNT_DOWN: 'B_SMS_COUNT_DOWN',
  B_ACCOUNT_CHECK_SMS_CODE: 'B_ACCOUNT_CHECK_SMS_CODE',
  B_ACCOUNT_SIGNUP: 'B_ACCOUNT_SIGNUP',
  B_SHOP_GET: 'B_SHOP_GET',
  B_SHOP_RESET: 'B_SHOP_RESET',
  B_SHOP_EDIT_COMMENT: 'B_SHOP_EDIT_COMMENT',
  B_SHOP_UNBIND: 'B_SHOP_UNBIND',
  B_ACCOUNT_GET_SIGNUP: 'B_ACCOUNT_GET_SIGNUP'
}
