/**
 * Created by fanli on 2017/5/6.
 */
export const A_TEAM_INDEX_GETLIST = 'A_TEAM_INDEX_GETLIST'
export const A_TEAM_DETAIL_GETDETAIL = 'A_TEAM_DETAIL_GETDETAIL'
export const A_TEAM_ADDTEAM = 'A_TEAM_ADDTEAM'
export const A_TEAM_CHANGE_WORK_STATE = 'A_TEAM_CHANGE_WORK_STATE'
export const A_TEAM_GET_DIMISSION_BDLIST = 'A_TEAM_GET_DIMISSION_BDLIST'
