/**
 * Created by fanli on 2017/5/6.
 */
export const A_COUNT_GETCOUNT = 'A_COUNT_GETCOUNT'
export const A_COUNT_GETRECORD = 'A_COUNT_GETRECORD'
export const A_COUNT_GETRECORD_DETAIL = 'A_COUNT_GETRECORD_DETAIL'
export const A_COUNT_GETRECORD_LIST = 'A_COUNT_GETRECORD_LIST'
export const A_COUNT_GETCASHRECORD_LIST = 'A_COUNT_GETCASHRECORD_LIST'
export const A_COUNT_CASH = 'A_COUNT_CASH'
export const A_COUNT_CASH_CHARGE = 'A_COUNT_CASH_CHARGE'
export const A_COUNT_CASH_MANAGE_DETAIL = 'A_COUNT_CASH_MANAGE_DETAIL'
export const A_COUNT_CASH_MANAGE_LIST = 'A_COUNT_CASH_MANAGE_LIST'
export const A_COUNT_GET_PAY_TYPE = 'A_COUNT_GET_PAY_TYPE'

