export default {
  SHOP_ALLOCATE_INDEX_GET_LIST: 'SHOP_ALLOCATE_INDEX_GET_LIST',
  SHOP_ALLOCATE_INDEX_GET_TAB_OPTION: 'SHOP_ALLOCATE_INDEX_GET_TAB_OPTION',
  SHOP_ALLOCATE_CHOSE_GET_LIST: 'SHOP_ALLOCATE_CHOSE_GET_LIST',
  SHOP_ALLOCATE_CHOSE_GET_SAVE_BD: 'SHOP_ALLOCATE_CHOSE_GET_SAVE_BD',
  SHOP_ALLOCATE_INDEX_GET_ALLOTLIST: 'SHOP_ALLOCATE_INDEX_GET_ALLOTLIST'
}
