export default {
  SHOP_BOXAPPLY_INDEX_GET_MAXNUM: 'SHOP_BOXAPPLY_INDEX_GET_MAXNUM',
  SHOP_BOXAPPLY_INDEX_GET_APPLYINFO: 'SHOP_BOXAPPLY_INDEX_GET_APPLYINFO',
  SHOP_BOXAPPLY_INDEX_GET_LOGININFO: 'SHOP_BOXAPPLY_INDEX_GET_LOGININFO',
  SHOP_BOXAPPLY_INDEX_GET_SUBMITBOX: 'SHOP_BOXAPPLY_INDEX_GET_SUBMITBOX'
}
