export const POI_LOCATED = 'POI_LOCATED'
export const POI_CHANGE = 'POI_CHANGE'
export const FETCH_SHOP_POSITION_CITIES = 'FETCH_SHOP_POSITION_CITIES'
export const FETCH_SHOP_POSITION_WAIT_INSTALL_SHOPS = 'FETCH_SHOP_POSITION_WAIT_INSTALL_SHOPS'
