export const ACCOUNT_GET_SMS_CODE = 'ACCOUNT_GET_SMS_CODE'
export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN'
export const SMS_COUNT_DOWN = 'SMS_COUNT_DOWN'
export const CLEAN_LOGIN_INFO = 'CLEAN_LOGIN_INFO'
