export default {
  COMMON_GET_BD_MEMBERS_IN_CITY: 'COMMON_GET_BD_MEMBERS_IN_CITY',
  COMMON_GET_MONTHLIST: 'COMMON_GET_MONTHLIST',
  COMMON_GET_AGENT_LEVEL: 'COMMON_GET_AGENT_LEVEL',
  COMMON_GET_CITY: 'COMMON_GET_CITY',
  COMMON_GET_AREA: 'COMMON_GET_AREA',
  COMMON_GET_DISTRIC: 'COMMON_GET_DISTRIC',
  COMMON_GET_SHOP_TYPE: 'COMMON_GET_SHOP_TYPE',
  COMMON_GET_OFFLINE_REASON: 'COMMON_GET_OFFLINE_REASON',
  COMMON_GET_ALL_MEMBERS_IN_CITY: 'COMMON_GET_ALL_MEMBERS_IN_CITY'
}
