export default {
  SHOP_EDIT_INDEX_GET_CHANGENAME: 'SHOP_EDIT_INDEX_GET_CHANGENAME',
  SHOP_EDIT_INDEX_GET_EDIT: 'SHOP_EDIT_INDEX_GET_EDIT',
  SHOP_EDIT_INDEX_GET_CHANGEMOBILE: 'SHOP_EDIT_INDEX_GET_CHANGEMOBILE'
}
