export const FETCH_USER_CHECK_ROLE = 'FETCH_USER_CHECK_ROLE'
export const FETCH_USER_CHOSE_ROLE = 'FETCH_USER_CHOSE_ROLE'
export const CLEAN_ROLE = 'CLEAN_ROLE'
export const GET_OPTIONS = 'GET_OPTIONS'
