export const REPLACE_BD_GET_CHANGE_SHOP_LIST = 'REPLACE_BD_GET_CHANGE_SHOP_LIST'
export const REPLACE_BD_GET_CONDITION_BY_AGENT = 'REPLACE_BD_GET_CONDITION_BY_AGENT'
export const REPLACE_BD_SHOP_ALLOCATE = 'REPLACE_BD_SHOP_ALLOCATE'
export const REPLACE_BD_REPLACE_BD = 'REPLACE_BD_REPLACE_BD'