export const A_ACCOUNT_GET_SMS_CODE = 'A_ACCOUNT_GET_SMS_CODE'
export const A_ACCOUNT_LOGIN = 'A_ACCOUNT_LOGIN'
export const A_SMS_COUNT_DOWN = 'A_SMS_COUNT_DOWN'
export const A_CLEAN_LOGIN_INFO = 'A_CLEAN_LOGIN_INFO'
