export default {
  CHANNEL_AGENT_GET_LIST: 'CHANNEL_AGENT_GET_LIST',
  CHANNEL_AGENT_GET_SEARCH_LIST: 'CHANNEL_AGENT_GET_SEARCH_LIST',
  CHANNEL_AGENT_GET_AGENT_INFO: 'CHANNEL_AGENT_GET_AGENT_INFO',
  CHANNEL_AGENT_POST_SAVE_AGENT: 'CHANNEL_AGENT_POST_SAVE_AGENT',
  CHANNEL_AGENT_POST_UPDATE_AGENT: 'CHANNEL_AGENT_POST_UPDATE_AGENT',
  CHANNEL_AGENT_TRIGGER_UPDATE_AGENT_INFO: 'CHANNEL_AGENT_TRIGGER_UPDATE_AGENT_INFO',
  CHANNEL_AGENT_TRIGGER_CLEAN_EDIT_INFO: 'CHANNEL_AGENT_TRIGGER_CLEAN_EDIT_INFO'
}
