export default {
  CHANNEL_AGENT_BD_GET_LIST: 'CHANNEL_AGENT_BD_GET_LIST',
  CHANNEL_AGENT_BD_GET_SEARCH_LIST: 'CHANNEL_AGENT_BD_GET_SEARCH_LIST',
  CHANNEL_AGENT_BD_GET_AGENT_INFO: 'CHANNEL_AGENT_BD_GET_AGENT_INFO',
  CHANNEL_AGENT_BD_POST_SAVE_AGENT: 'CHANNEL_AGENT_BD_POST_SAVE_AGENT',
  CHANNEL_AGENT_BD_POST_UPDATE_AGENT: 'CHANNEL_AGENT_BD_POST_UPDATE_AGENT',
  CHANNEL_BD_AGENT_TRIGGER_UPDATE_AGENT_INFO: 'CHANNEL_BD_AGENT_TRIGGER_UPDATE_AGENT_INFO',
  CHANNEL_AGENT_BD_TRIGGER_CLEAN_EDIT_INFO: 'CHANNEL_AGENT_BD_TRIGGER_CLEAN_EDIT_INFO',
  CHANNEL_AGENT_BD_TRIGGER_UPDATE_AGENT_INFO: 'CHANNEL_AGENT_BD_TRIGGER_UPDATE_AGENT_INFO'
}
