export default {
  CHANNEL_PURCHASE_GET_LIST: 'CHANNEL_PURCHASE_GET_LIST',
  CHANNEL_PURCHASE_POST_APPROVAL: 'CHANNEL_PURCHASE_POST_APPROVAL',
  CHANNEL_PURCHASE_POST_SAVE_EXPRESS: 'CHANNEL_PURCHASE_POST_SAVE_EXPRESS'
}
